services:
  # Il nuovo servizio Redis, gestito da Compose.
  redis_cache:
    image: redis:alpine
    container_name: redis_cache
    networks:
      - signage_network
    restart: unless-stopped

  nginx_proxy:
    container_name: nginx_proxy
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - signage_network
    depends_on:
      - redis_cache         # Aggiunta dipendenza
      - telegram_service
      - schedule_service
      - floorplan_service
      - wayfinding_service
    restart: unless-stopped

  telegram_service:
    container_name: telegram_service
    build: ./telegram-service
    env_file:
      - ./telegram-service/.env
    volumes:
      - ./telegram-service/data:/app/data
    networks:
      - signage_network
    restart: unless-stopped

  schedule_service:
    container_name: schedule_service
    build: ./schedule-service
    env_file:
      - ./schedule-service/.env
    networks:
      - signage_network
    restart: unless-stopped
    depends_on:
      - redis_cache

  floorplan_service:
    container_name: floorplan_service
    build: ./floorplan-service
    networks:
      - signage_network
    restart: unless-stopped

  wayfinding_service:
    container_name: wayfinding_service
    build: ./wayfinding-service
    networks:
      - signage_network
    restart: unless-stopped

  totem_service:
    container_name: totem_service
    build: ./totem-service
    networks:
      - signage_network
    restart: unless-stopped

  time_service:
    container_name: time_service
    build: ./time-service
    networks:
      - signage_network
    restart: unless-stopped

networks:
  signage_network:
    driver: bridge