services:
  telegram_feed:
    container_name: telegram_feed_service
    build:
      context: ./telegram-feed-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./telegram-feed-service/.env
    volumes:
      - ./telegram-feed-service/data:/app/data
    networks:
      - signage_network
    restart: unless-stopped

  schedule_display:
    container_name: schedule_display_service
    build:
      context: ./schedule-display-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - ./schedule-display-service/.env
    networks:
      - signage_network
    restart: unless-stopped

  floorplan_display:
    container_name: floorplan_display_service
    build:
      context: ./floorplan-display-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - signage_network
    restart: unless-stopped

  wayfinding:
    container_name: wayfinding_service
    build:
      context: ./wayfinding-service
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    networks:
      - signage_network
    restart: unless-stopped

networks:
  signage_network:
    driver: bridge