services:
  telegram_service:
    container_name: telegram_service
    build:
      context: ./telegram-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./telegram-service/.env
    volumes:
      - ./telegram-service/data:/app/data
    networks:
      - signage_network
    restart: unless-stopped

  schedule_service:
    container_name: schedule_service
    build:
      context: ./schedule-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - ./schedule-service/.env
    networks:
      - signage_network
    restart: unless-stopped

  floorplan_service:
    container_name: floorplan_service
    build:
      context: ./floorplan-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - signage_network
    restart: unless-stopped

  wayfinding_service:
    container_name: wayfinding_service
    build:
      context: ./wayfinding-service
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    networks:
      - signage_network
    restart: unless-stopped

networks:
  signage_network:
    driver: bridge